services:

  app:
    image: node:latest 
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000" #
    command: sh -c "npm install && npm run build && npm run dev"

    depends_on:
      - mysql
    networks:
      - tareasnetwork

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: True
      MYSQL_ROOT_PASSWORD:   
      MYSQL_DATABASE: "gestiontareas" 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./gestiontareas.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tareasnetwork

volumes:
  db_data:

networks:
  tareasnetwork: